---
- name: Deploy T2S Website
  hosts: all
  become: yes
  tasks:
    - name: Install Python on Debian-based systems
      raw: |
        sudo apt update && sudo apt install -y python3 python3-apt
      when: ansible_facts['os_family'] == 'Debian'
      changed_when: false

    - name: Install Python on Red Hat-based systems
      raw: |
        sudo yum update -y && sudo yum install -y python3
      when: ansible_facts['os_family'] == 'RedHat'
      changed_when: false

    - name: Install Nginx
      package:
        name: nginx
        state: present
        update_cache: yes

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy website files
      copy:
        src: webapp/index.html
        dest: "{{ '/var/www/html/index.html' if ansible_facts['os_family'] == 'Debian' else '/usr/share/nginx/html/index.html' }}"
        owner: root
        group: root
        mode: '0644'

    - name: Adjust permissions on web server files
      file:
        path: "{{ '/var/www/html' if ansible_facts['os_family'] == 'Debian' else '/usr/share/nginx/html' }}"
        owner: "{{ 'www-data' if ansible_facts['os_family'] == 'Debian' else 'nginx' }}"
        group: "{{ 'www-data' if ansible_facts['os_family'] == 'Debian' else 'nginx' }}"
        recurse: yes
